spring:
  application:
    name: neighborhood
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/neighborhood
    username: neighborhood
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    baseline:
      on-migrate: true
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    path: /api-docs