create TABLE flyway_schema_history (
  installed_rank INTEGER NOT NULL,
   version VARCHAR(50),
   description VARCHAR(200) NOT NULL,
   type VARCHAR(20) NOT NULL,
   script VARCHAR(1000) NOT NULL,
   checksum INTEGER,
   installed_by VARCHAR(100) NOT NULL,
   installed_on TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
   execution_time INTEGER NOT NULL,
   success BOOLEAN NOT NULL,
   CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

create TABLE chat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT chat_pkey PRIMARY KEY (id)
);

create TABLE chat_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   message VARCHAR(255),
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   chat_id BIGINT,
   player_id BIGINT,
   CONSTRAINT chat_message_pkey PRIMARY KEY (id)
);

create TABLE court (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   name VARCHAR(255),
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   park_id BIGINT,
   CONSTRAINT court_pkey PRIMARY KEY (id)
);

create TABLE friendship (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT friendship_pkey PRIMARY KEY (id)
);

create TABLE notification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   message INTEGER,
   read BOOLEAN NOT NULL,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   player_id BIGINT,
   CONSTRAINT notification_pkey PRIMARY KEY (id)
);

create TABLE park (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   location VARCHAR(255) NOT NULL,
   name VARCHAR(255),
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT park_pkey PRIMARY KEY (id)
);

create TABLE player (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   archetype VARCHAR(255),
   birthdate TIMESTAMP WITHOUT TIME ZONE,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   email VARCHAR(255),
   experience BIGINT,
   height SMALLINT,
   level BIGINT,
   name VARCHAR(255) NOT NULL,
   nickname VARCHAR(255),
   password VARCHAR(255),
   position VARCHAR(255),
   role VARCHAR(255),
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   weight SMALLINT,
   friendship_id BIGINT,
   CONSTRAINT player_pkey PRIMARY KEY (id)
);

create TABLE player_career_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   assists_per_game FLOAT8,
   blocks_per_game FLOAT8,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   league VARCHAR(255),
   minutes_per_game FLOAT8,
   points_per_game FLOAT8,
   rebounds_per_game FLOAT8,
   steals_per_game FLOAT8,
   team VARCHAR(255),
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   player_id BIGINT,
   CONSTRAINT player_career_history_pkey PRIMARY KEY (id)
);

create TABLE player_street_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   assists BIGINT,
   block BIGINT,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   points BIGINT,
   rebounds BIGINT,
   steals BIGINT,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   verified BOOLEAN,
   won BOOLEAN,
   player_id BIGINT,
   CONSTRAINT player_street_stats_pkey PRIMARY KEY (id)
);

create TABLE street_game (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   accepted BOOLEAN,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   game_mode VARCHAR(255),
   scheduled_at TIMESTAMP WITHOUT TIME ZONE,
   status VARCHAR(255),
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   court_id BIGINT,
   CONSTRAINT street_game_pkey PRIMARY KEY (id)
);

create index flyway_schema_history_s_idx on flyway_schema_history(success);

alter table player add CONSTRAINT uk_oivbimcon0iqmb8efpv723h08 UNIQUE (email);

create TABLE player_chats (
  player_id BIGINT NOT NULL,
   chats_id BIGINT NOT NULL,
   CONSTRAINT player_chats_pkey PRIMARY KEY (player_id, chats_id)
);

create TABLE player_street_games (
  player_id BIGINT NOT NULL,
   street_games_id BIGINT NOT NULL,
   CONSTRAINT player_street_games_pkey PRIMARY KEY (player_id, street_games_id)
);

alter table notification add CONSTRAINT fk1qdrvn9j90lv095ok6fx19rin FOREIGN KEY (player_id) REFERENCES player (id) ON update NO ACTION ON delete NO ACTION;

alter table street_game add CONSTRAINT fk38q67scviogwxs420w9fsullu FOREIGN KEY (court_id) REFERENCES court (id) ON update NO ACTION ON delete NO ACTION;

alter table court add CONSTRAINT fk62o7x7u2bp4djs773xgs12m5h FOREIGN KEY (park_id) REFERENCES park (id) ON update NO ACTION ON delete NO ACTION;

alter table chat_message add CONSTRAINT fkax7xe8g71nf0wvpoychqkqeid FOREIGN KEY (chat_id) REFERENCES chat (id) ON update NO ACTION ON delete NO ACTION;

alter table player_career_history add CONSTRAINT fkayf5c3eq4wtdtxpuhlyt3wt4n FOREIGN KEY (player_id) REFERENCES player (id) ON update NO ACTION ON delete NO ACTION;

alter table player_street_games add CONSTRAINT fkc12ujnao28io827cavcvbhkkf FOREIGN KEY (street_games_id) REFERENCES street_game (id) ON update NO ACTION ON delete NO ACTION;

alter table player add CONSTRAINT fkcbktjn3objnquauot7amb1g82 FOREIGN KEY (friendship_id) REFERENCES friendship (id) ON update NO ACTION ON delete NO ACTION;

alter table player_street_games add CONSTRAINT fkfghncetl7jefa3xq0hahq118i FOREIGN KEY (player_id) REFERENCES player (id) ON update NO ACTION ON delete NO ACTION;

alter table player_street_stats add CONSTRAINT fklbgmqdcnrlm4q0gv32xwym892 FOREIGN KEY (player_id) REFERENCES player (id) ON update NO ACTION ON delete NO ACTION;

alter table chat_message add CONSTRAINT fkme5n7vo6ptyu8uvib8aijqpew FOREIGN KEY (player_id) REFERENCES player (id) ON update NO ACTION ON delete NO ACTION;

alter table player_chats add CONSTRAINT fkodto8d623ara3fap5jqh0yimj FOREIGN KEY (chats_id) REFERENCES chat (id) ON update NO ACTION ON delete NO ACTION;

alter table player_chats add CONSTRAINT fkqt8ycci8etpog6sytant4glnc FOREIGN KEY (player_id) REFERENCES player (id) ON update NO ACTION ON delete NO ACTION;